In [2]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [3]:
#data = pd.read_excel('resmiyet.xlsx')
# data = pd.read_excel('resmiyetV2.xlsx')
data = pd.read_excel('resmiyetV2.xlsx')

In [4]:
data.head(5)

Cümle  Resmiyet
0                 Toplantı saati değiştirildi.        10
1              Size nasıl yardımcı olabilirim?         8
2  Görüşme planlarımızı netleştirebilir miyiz?        10
3    Lütfen bana detayları iletebilir misiniz?         7
4   Şirket politikası gereği bunu yapamıyoruz.        10

In [5]:
vector = TfidfVectorizer()
x = vector.fit_transform(data['Cümle'])
y = data["Resmiyet"]

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [7]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [8]:
simulator = model.predict(x_test)

In [9]:
print(mean_squared_error(y_test,simulator))
model.score(x_test,y_test)

0.9946861146179033


0.8837530741708295

In [10]:
model.predict(vector.transform(["pompala aşkım ohhh"]))

array([3.05865288])

In [11]:
model.predict(vector.transform(["Merhaba, nasıl olduğunuzdan eminim ama bu hafta biraz daha yoğun olacağım. Eğer uygun görürseniz, bu hafta sonu bir araya gelip daha detaylı bir şekilde konuşabiliriz. Ne zaman müsait olursanız, haber verirseniz sevinirim."]))

array([4.96302841])

In [12]:
model.predict(vector.transform(['Sayın yetkili, başvurunuz değerlendirmeye alınmıştır.']))

array([5.58703051])

In [13]:
model.predict(vector.transform(['Sayın Müşterimiz, başvurunuz tarafımıza ulaşmış olup, ilgili birim tarafından detaylı olarak incelendikten sonra en kısa sürede tarafınıza geri dönüş sağlanacaktır. İlginiz için teşekkür ederiz.']))

array([7.71116058])

In [14]:
model.predict(vector.transform(['']))

array([5.58703051])

In [15]:
print(mean_squared_error(y_test,simulator))

0.9946861146179033


In [16]:
model.coef_

array([-1.05146385,  1.45648402, -1.65858122,  0.40292624, -2.52837763,
       -1.40923098,  1.0421634 ,  2.01451411, -2.06760231,  1.28552442,
       -1.62829033,  0.40292624, -0.16285596, -1.43027726, -1.5907511 ,
       -2.53353857, -0.08668214, -0.4691511 , -1.31340796, -0.43117859,
       -0.95447912,  1.71056535, -1.91903269,  1.0421634 ,  1.45648402,
        1.13771716,  1.50818934,  1.13771716,  1.43360166,  1.70486813,
        1.38698524,  1.69166901, -1.91903269,  1.38698524,  1.55194791,
       -0.87953626, -1.40923098,  1.71056535,  1.45648402, -1.77776811,
       -1.65858122, -0.95447912,  1.57873393,  1.45648402, -1.65681578,
       -2.53353857,  1.38698524, -2.02686858, -0.92498986, -2.06760231,
        1.0421634 ,  1.71056535,  0.70462781, -1.77776811, -0.95447912,
       -1.77776811, -1.40923098, -2.54243254,  0.40292624, -1.40923098,
        1.71056535, -0.95447912,  1.0421634 , -0.95447912, -1.05146385,
       -1.77776811,  0.40292624,  2.66341185,  0.84224891, -0.35

In [17]:
futures = vector.get_feature_names_out()
vector.get_feature_names_out()

array(['aldım', 'anlaşmanın', 'arkadaşlarla', 'açabilir', 'aşkım',
       'bakmayın', 'bana', 'başlatılmıştır', 'beklemiyordum', 'belli',
       'bir', 'biraz', 'birlikte', 'bu', 'bugün', 'buluşalım',
       'buluşuyoruz', 'bunu', 'böyle', 'daha', 'defa', 'departmanla',
       'ders', 'detayları', 'detaylarını', 'değerlendireceğim',
       'değiştirildi', 'dönüş', 'edebilir', 'ederim', 'edilmesi',
       'erkenden', 'gerekiyor', 'gerekmektedir', 'gereği', 'gerçekten',
       'geç', 'geçildi', 'geçireceğim', 'gidelim', 'gittik', 'gördüm',
       'görüşme', 'gözden', 'güzel', 'hadi', 'hareket', 'harikaydı',
       'hava', 'hiç', 'iletebilir', 'iletişime', 'için', 'içmeye',
       'kadar', 'kahve', 'kaldım', 'kanka', 'konuyu', 'kusura', 'lgili',
       'lk', 'lütfen', 'manzara', 'memnunum', 'mi', 'misin', 'misiniz',
       'miyiz', 'mı', 'napıyon', 'napıyosun', 'nasıl', 'ne',
       'netleştirebilir', 'of', 'olabilirim', 'olacaktı', 'oldu',
       'paylaşabilir', 'planlarımızı', 'planın',

In [18]:
'''
with open('database', "r") as file:
    text = file.read()

words = text.lower().split()

def newWordBefore(search_phrase):
    search_words = search_phrase.split()
    sub_length = len(search_words)

    found_positions = []

    # Önce tam cümleyi bul
    for i in range(len(words) - sub_length + 1):
        if words[i:i + sub_length] == search_words:
            prev_word = words[i - 1] if i > 0 else None
            position = i + 1
            print(f"Cümle: '{search_phrase}' {position}. kelime, önceki kelime: '{prev_word}'." if prev_word else f"Cümle: '{search_phrase}' {position}. kelime, önceki kelime: Yok.")
            found_positions.append(i)  # Konumu kaydet

    print("-" * 50)

    # Şimdi sadece ilk kelimeyi ("bir") ayrıca kontrol et, ama diğerlerini etme!
    first_word = search_words[0]

    for i in range(len(words)):
        if words[i] == first_word and i not in found_positions:
            prev_word = words[i - 1] if i > 0 else None
            position = i + 1
            print(f"Cümle: '{first_word}' {position}. kelime, önceki kelime: '{prev_word}'." if prev_word else f"Cümle: '{first_word}' {position}. kelime, önceki kelime: Yok.")

    print("=" * 50)


def newWordNext(search_phrase):
    search_words = search_phrase.split()
    sub_length = len(search_words)

    found_positions = []

    # Önce tam cümleyi bul
    for i in range(len(words) - sub_length + 1):
        if words[i:i + sub_length] == search_words:
            next_word = words[i + sub_length] if i + sub_length < len(words) else None
            position = i + 1
            print(f"Cümle: '{search_phrase}' {position}. kelime, bir sonraki kelime: '{next_word}'." if next_word else f"Cümle: '{search_phrase}' {position}. kelime, bir sonraki kelime: Yok.")
            found_positions.append(i)

    print("-" * 50)

    # Sadece ilk kelimeyi ("bir") kontrol et
    first_word = search_words[0]

    for i in range(len(words)):
        if words[i] == first_word and i not in found_positions:
            next_word = words[i + 1] if i + 1 < len(words) else None
            position = i + 1
            print(f"Cümle: '{first_word}' {position}. kelime, bir sonraki kelime: '{next_word}'." if next_word else f"Cümle: '{first_word}' {position}. kelime, bir sonraki kelime: Yok.")

    print("=" * 50)
'''

from collections import Counter

with open('database', "r") as file:
    text = file.read()

words = text.lower().split()

def find_middle_words(word1, word2):
    """Kelime1'den sonra en yakın Kelime2'ye kadar olan kelimeleri bulur"""
    middle_words = []
    i = 0

    while i < len(words):
        if words[i] == word1:
            # "word1" bulundu, şimdi en yakın "word2"yi ara
            j = i + 1
            while j < len(words) and words[j] != word2:
                middle_words.append(words[j])
                j += 1
            i = j  # "word2"ye ulaşıldıysa atla
        else:
            i += 1

    # En çok tekrar eden kelimeyi bul
    if middle_words:
        word_counts = Counter(middle_words)
        most_common_word, count = word_counts.most_common(1)[0]
        print(f"'{word1}' ve '{word2}' arasındaki en çok geçen kelime: '{most_common_word}' ({count} kez)")
    else:
        print(f"'{word1}' ve '{word2}' arasında ortak kelime bulunamadı.")

# Örnek kullanım
find_middle_words("fatih", "mehmet")



'fatih' ve 'mehmet' arasındaki en çok geçen kelime: '.' (241368 kez)


In [34]:
##
## indirgeme modülü

from difflib import get_close_matches

def reWrite(cumle, futures, esik=0.85):
    kelimeler = cumle.split()
    duzeltilmis_kelimeler = []

    for kelime in kelimeler:
        yakin_kelimeler = get_close_matches(kelime, futures, n=1, cutoff=esik)
        if yakin_kelimeler:
            duzeltilmis_kelimeler.append(yakin_kelimeler[0])
        else:
            duzeltilmis_kelimeler.append(kelime)

    return " ".join(duzeltilmis_kelimeler)



# Örnek cümle
cumle = "merhava arkadaşlar"

# Çalıştır
duzgun_cumle = reWrite(cumle, futures)
print(duzgun_cumle)


merhava arkadaşlarla


In [33]:
 while True:
    search_phrase = input("Cümle: ").strip()
    search_words = search_phrase.split()

    temp = 0
    for word in search_words:
      temp += model.predict(vector.transform([reWrite(word, futures)]))
      print(temp)

    ort = temp / len(search_words) # cümledeki kelimelerin ortalama ağırlık değeri
    print(f"ortalama ağırlık değeri = {ort}")

    print("Cümle taranıyor...")
    for word in search_words:
      if abs(model.predict(vector.transform([reWrite(word, futures)])) - ort) >= 1:
        print(f"yakalanan kelime >> '{word}'")
        InputSet = " ".join(search_words[:search_words.index(word)]) # algoritmaya girecek kısım
        newWordNext(InputSet)

KeyboardInterrupt: Interrupted by user

In [ ]:
### TEST MODÜLÜ

#newWordNext("bir gün")
#newWordBefore("bir gün")
find_common_words("bir gün")

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-38-b762b60bea35>", line 5, in <cell line: 0>
    find_common_words("bir gün")
  File "<ipython-input-37-16b7a9d081f2>", line 100, in find_common_words
    next_words = get_next_words(search_phrase)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ipython-input-37-16b7a9d081f2>", line None, in get_next_words
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2099, in showtraceback
    stb = value._render_traceback_()
          ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback