In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [ ]:
#data = pd.read_excel('resmiyet.xlsx')
# data = pd.read_excel('resmiyetV2.xlsx')
data = pd.read_excel('resmiyetV2.xlsx')

In [ ]:
data.head(5)

Cümle  Resmiyet
0                 Toplantı saati değiştirildi.        10
1              Size nasıl yardımcı olabilirim?         8
2  Görüşme planlarımızı netleştirebilir miyiz?        10
3    Lütfen bana detayları iletebilir misiniz?         7
4   Şirket politikası gereği bunu yapamıyoruz.        10

In [ ]:
vector = TfidfVectorizer()
x = vector.fit_transform(data['Cümle'])
y = data["Resmiyet"]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
simulator = model.predict(x_test)

In [ ]:
print(mean_squared_error(y_test,simulator))
model.score(x_test,y_test)

0.9946861146179033


0.8837530741708295

In [ ]:
model.predict(vector.transform(["Projeyi tamamladınız mı?"]))

array([5.22966655])

In [ ]:
model.predict(vector.transform(["Merhaba, nasıl olduğunuzdan eminim ama bu hafta biraz daha yoğun olacağım. Eğer uygun görürseniz, bu hafta sonu bir araya gelip daha detaylı bir şekilde konuşabiliriz. Ne zaman müsait olursanız, haber verirseniz sevinirim."]))

array([4.96302841])

In [ ]:
model.predict(vector.transform(['Sayın yetkili, başvurunuz değerlendirmeye alınmıştır.']))

array([5.58703051])

In [ ]:
model.predict(vector.transform(['Sayın Müşterimiz, başvurunuz tarafımıza ulaşmış olup, ilgili birim tarafından detaylı olarak incelendikten sonra en kısa sürede tarafınıza geri dönüş sağlanacaktır. İlginiz için teşekkür ederiz.']))

array([7.71116058])

In [ ]:
model.predict(vector.transform(['']))

array([5.58703051])

In [ ]:
print(mean_squared_error(y_test,simulator))

0.9946861146179033


In [ ]:
model.coef_

array([-1.05146385,  1.45648402, -1.65858122,  0.40292624, -2.52837763,
       -1.40923098,  1.0421634 ,  2.01451411, -2.06760231,  1.28552442,
       -1.62829033,  0.40292624, -0.16285596, -1.43027726, -1.5907511 ,
       -2.53353857, -0.08668214, -0.4691511 , -1.31340796, -0.43117859,
       -0.95447912,  1.71056535, -1.91903269,  1.0421634 ,  1.45648402,
        1.13771716,  1.50818934,  1.13771716,  1.43360166,  1.70486813,
        1.38698524,  1.69166901, -1.91903269,  1.38698524,  1.55194791,
       -0.87953626, -1.40923098,  1.71056535,  1.45648402, -1.77776811,
       -1.65858122, -0.95447912,  1.57873393,  1.45648402, -1.65681578,
       -2.53353857,  1.38698524, -2.02686858, -0.92498986, -2.06760231,
        1.0421634 ,  1.71056535,  0.70462781, -1.77776811, -0.95447912,
       -1.77776811, -1.40923098, -2.54243254,  0.40292624, -1.40923098,
        1.71056535, -0.95447912,  1.0421634 , -0.95447912, -1.05146385,
       -1.77776811,  0.40292624,  2.66341185,  0.84224891, -0.35

In [ ]:
futures = vector.get_feature_names_out()
vector.get_feature_names_out()

array(['aldım', 'anlaşmanın', 'arkadaşlarla', 'açabilir', 'aşkım',
       'bakmayın', 'bana', 'başlatılmıştır', 'beklemiyordum', 'belli',
       'bir', 'biraz', 'birlikte', 'bu', 'bugün', 'buluşalım',
       'buluşuyoruz', 'bunu', 'böyle', 'daha', 'defa', 'departmanla',
       'ders', 'detayları', 'detaylarını', 'değerlendireceğim',
       'değiştirildi', 'dönüş', 'edebilir', 'ederim', 'edilmesi',
       'erkenden', 'gerekiyor', 'gerekmektedir', 'gereği', 'gerçekten',
       'geç', 'geçildi', 'geçireceğim', 'gidelim', 'gittik', 'gördüm',
       'görüşme', 'gözden', 'güzel', 'hadi', 'hareket', 'harikaydı',
       'hava', 'hiç', 'iletebilir', 'iletişime', 'için', 'içmeye',
       'kadar', 'kahve', 'kaldım', 'kanka', 'konuyu', 'kusura', 'lgili',
       'lk', 'lütfen', 'manzara', 'memnunum', 'mi', 'misin', 'misiniz',
       'miyiz', 'mı', 'napıyon', 'napıyosun', 'nasıl', 'ne',
       'netleştirebilir', 'of', 'olabilirim', 'olacaktı', 'oldu',
       'paylaşabilir', 'planlarımızı', 'planın',

In [ ]:
with open('database', "r") as file:
    text = file.read()

words = text.lower().split()

def newWordBefore(search_phrase):
    search_words = search_phrase.split()

    for start in range(len(search_words)):
        sub_phrase = search_words[start:]
        sub_length = len(sub_phrase)

        for i in range(len(words) - sub_length + 1):
            if words[i:i + sub_length] == sub_phrase:
                prev_word = words[i - 1] if i > 0 else None  # Bir önceki kelimeyi bul
                position = i + 1
                print(f"Cümle: '{' '.join(sub_phrase)}' {position}. kelime, önceki kelime: '{prev_word}'." if prev_word else f"Cümle: '{' '.join(sub_phrase)}' {position}. kelime, önceki kelime: Yok.")

        print("-" * 50)

############################################################

def newWordNext(search_phrase):
    search_words = search_phrase.split()


    for start in range(len(search_words)):
        sub_phrase = search_words[start:]
        sub_length = len(sub_phrase)

        for i in range(len(words) - sub_length + 1):
            if words[i:i + sub_length] == sub_phrase:
                next_word = words[i + sub_length] if i + sub_length < len(words) else None
                position = i + 1
                print(f"Cümle: '{' '.join(sub_phrase)}' {position}. kelime, bir sonraki kelime: '{next_word}'." if next_word else f"Cümle: '{' '.join(sub_phrase)}' {position}. kelime, bir sonraki kelime: Yok.")

        print("-" * 50)


In [ ]:
##
## indirgeme modülü

from difflib import get_close_matches

def reWrite(cumle, futures, esik=0.85):
    kelimeler = cumle.split()
    duzeltilmis_kelimeler = []

    for kelime in kelimeler:
        yakin_kelimeler = get_close_matches(kelime, futures, n=1, cutoff=esik)
        if yakin_kelimeler:
            duzeltilmis_kelimeler.append(yakin_kelimeler[0])
        else:
            duzeltilmis_kelimeler.append(kelime)

    return " ".join(duzeltilmis_kelimeler)



# Örnek cümle
cumle = "merhava arkadaşlar"

# Çalıştır
duzgun_cumle = reWrite(cumle, futures)
print(duzgun_cumle)


merhava arkadaşlarla


In [ ]:
 while True:
    search_phrase = input("Cümle: ").strip()
    search_words = search_phrase.split()

    temp = 0
    for word in search_words:
      temp += model.predict(vector.transform([reWrite(word, futures)]))
      print(temp)

    ort = temp / len(search_words) # cümledeki kelimelerin ortalama ağırlık değeri
    print(f"ortalama ağırlık değeri = {ort}")

    print("Cümle taranıyor...")
    for word in search_words:
      if abs(model.predict(vector.transform([reWrite(word, futures)])) - ort) >= 1:
        print(f"yakalanan kelime >> '{word}'")
        InputSet = " ".join(search_words[:search_words.index(word)]) # algoritmaya girecek kısım


KeyboardInterrupt: Interrupted by user

In [ ]:
### TEST MODÜLÜ

#newWordNext("bir gün")
newWordBefore("bir gün")

Streaming output truncated to the last 5000 lines.
Cümle: 'gün' 8746866. kelime, önceki kelime: '90'.
Cümle: 'gün' 8746876. kelime, önceki kelime: '90'.
Cümle: 'gün' 8746890. kelime, önceki kelime: '30'.
Cümle: 'gün' 8746906. kelime, önceki kelime: '90'.
Cümle: 'gün' 8746934. kelime, önceki kelime: '14'.
Cümle: 'gün' 8746946. kelime, önceki kelime: '14'.
Cümle: 'gün' 8746957. kelime, önceki kelime: '30'.
Cümle: 'gün' 8746965. kelime, önceki kelime: '90'.
Cümle: 'gün' 8746977. kelime, önceki kelime: '30'.
Cümle: 'gün' 8746989. kelime, önceki kelime: '30'.
Cümle: 'gün' 8747001. kelime, önceki kelime: '180'.
Cümle: 'gün' 8747009. kelime, önceki kelime: '21'.
Cümle: 'gün' 8747018. kelime, önceki kelime: '90'.
Cümle: 'gün' 8747026. kelime, önceki kelime: '360'.
Cümle: 'gün' 8747037. kelime, önceki kelime: '30'.
Cümle: 'gün' 8747060. kelime, önceki kelime: '15'.
Cümle: 'gün' 8747076. kelime, önceki kelime: '90'.
Cümle: 'gün' 8747087. kelime, önceki kelime: '30'.
Cümle: 'gün' 8747101. kelime,